### PR TITLE
Van Routes

### PR DESCRIPTION
**Pull request by tbwrigh**

### CODE REVIEW

**Comment by tbwrigh** [comment]
Probably there is a better way to do the join like commands required for the include parameter for analytics.

**Review by OxygenCobalt — CHANGES_REQUESTED** [review]
Honestly, I'm not a fan of having the ridership data as an include parameter. I feel like it would be better as part of some kind of `GET /stats/ridership` route. This would allow more advanced filtering (by route, by van, by stop?) and also more advanced calculations.

**Comment by shanecranor** [comment]
> Honestly, I'm not a fan of having the ridership data as an include parameter. I feel like it would be better as part of some kind of `GET /stats/ridership` route. This would allow more advanced filtering (by route, by van, by stop?) and also more advanced calculations.

I think it is fine to keep the ridership data here as an optional param, but we definitely need the full ridership route to populate the admin panel

**Review by shanecranor — APPROVED** [review]

**Comment by tbwrigh** [comment]
@OxygenCobalt Yep, those routes are needed, but this should technically be available for include. If we change our minds later, we can remove then

**Review by OxygenCobalt — CHANGES_REQUESTED** [review]

**Review by OxygenCobalt — APPROVED** [review]

**Pull request merged**
